# site settings
title: My Website
email: alexi30401@gmail.com
description: > 
        This is a site description.
baseurl: ''
url: 'http://localhost:4000'
twitter_username: most_alyoshenka
github_username: alyoshenka

# build settings
sass:
        sass_dir: _sass

#other things
collections:
        authors:
                output: true

defaults:
        - scope:
                path: ""
                type: "authors"
          values:
                  layout: "author"
        - scope:
                path: ""
                type: "posts"
          values: 
                layout: "post"
        - scope:
                path: ""
          values:
                layout: "default"

